# Generated by Django 5.2 on 2025-04-24 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collects', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0, verbose_name='Slado')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='customers.customer', verbose_name='Cliente ID')),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(verbose_name='Total do depósito')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Deposit', to='accounts.account', verbose_name='Conta ID')),
                ('colect_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Deposit', to='collects.collect', verbose_name='Coleta ID')),
            ],
            options={
                'verbose_name': 'Depósito',
                'verbose_name_plural': 'Depósitos',
            },
        ),
    ]
