# Generated by Django 4.2.7 on 2025-04-25 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='colect_id',
            new_name='collect_id',
        ),
    ]
