# Generated by Django 5.2 on 2025-04-25 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.AddField(
            model_name='customer',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Privilégio'),
        ),
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(default='client', max_length=50, unique=True, verbose_name='Login'),
        ),
    ]
