# Generated by Django 5.2 on 2025-04-24 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, verbose_name='Categoria')),
                ('price', models.IntegerField(verbose_name='Preço')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=15, verbose_name='CEP')),
                ('street_address', models.CharField(max_length=50, verbose_name='Rua')),
                ('number', models.IntegerField(verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=60, null=True, verbose_name='Complemento')),
                ('neighborhood', models.CharField(max_length=50, verbose_name='Bairro')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Address', to='customers.customer', verbose_name='Cliente ID')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(verbose_name='Peso')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Criado em')),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Colect', to='collects.address', verbose_name='Endereço ID')),
                ('categorie_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Colect', to='collects.categorie', verbose_name='Categoria ID')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Colect', to='customers.customer', verbose_name='Cliente ID')),
            ],
            options={
                'verbose_name': 'Coleta',
                'verbose_name_plural': 'Coletas',
            },
        ),
    ]
