# Generated by Django 5.2 on 2025-05-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='bonus',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fator de Bonificação'),
        ),
    ]
