# Generated by Django 4.2.7 on 2025-04-25 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrators', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='user',
        ),
        migrations.AddField(
            model_name='administrator',
            name='is_staff',
            field=models.BooleanField(default=True, verbose_name='Privilégio'),
        ),
        migrations.AddField(
            model_name='administrator',
            name='username',
            field=models.CharField(default='admin', max_length=50, unique=True, verbose_name='Login'),
        ),
    ]
