# Generated by Django 4.2.7 on 2025-04-25 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrators', '0002_remove_administrator_user_administrator_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='administrator',
            name='username',
        ),
        migrations.AddField(
            model_name='administrator',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='administrators', to=settings.AUTH_USER_MODEL, verbose_name='Administrador'),
        ),
    ]
