# Generated by Django 5.2 on 2025-04-24 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(verbose_name='Valor total')),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='accounts.account', verbose_name='Conta ID')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customers.customer', verbose_name='Cliente ID')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='OrderProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.IntegerField(verbose_name='Quantidade de produto')),
                ('product_price', models.IntegerField(verbose_name='Valor do produto')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orderProducts', to='orders.order', verbose_name='Pedido ID')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orderProducts', to='products.product', verbose_name='Pedido ID')),
            ],
            options={
                'verbose_name': 'Pedido Produto',
                'verbose_name_plural': 'Pedido produtos',
            },
        ),
    ]
